### PR TITLE
Fix compile compatibility with last version

### PR DESCRIPTION
**Pull request by Koshub**

### CODE REVIEW

**Comment by alfredh** [comment]
thanks, I added your patch to upstream.

could you please remove the patch from this PR, and rebase ?
please also avoid unrelated whitespace changes.

**Comment by alfredh** [comment]
can you please resolve the conflicts ?

after that I am happy to merge it.

**Comment by Koshub** [comment]
@alfredh sorry, I am trying ((

**Comment by Koshub** [comment]
@alfredh I hope I make it🙂. Is this what you want me to do?

**Pull request merged**
